spring.application.name=career-graph-backend

server.port=8080

# CognoDB
cognodb.uri=${COGNODB_URI}
cognodb.username=${COGNODB_USERNAME:cognodb}
cognodb.password=${COGNODB_PASSWORD}
cognodb.database=${COGNODB_DATABASE:neo4j}

# JSON
spring.jackson.default-property-inclusion=non_null